{{- $fluxSettingsIstioOperator := merge .Values.istiooperator.flux .Values.flux -}}
{{- if .Values.istiooperator.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: istio-operator
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: istio-operator
  chart:
    spec:
      chart: {{ .Values.istiooperator.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: istio-operator
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsIstioOperator | nindent 2 }}

  {{- if .Values.istiooperator.postRenderers }}
  postRenderers:
  {{ toYaml .Values.istiooperator.postRenderers | nindent 4 }}
  {{- end }}
  valuesFrom:
    - name: {{ .Release.Name }}-istio-operator-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-istio-operator-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-istio-operator-values
      kind: Secret
      valuesKey: "overlays"

  {{- if .Values.gatekeeper.enabled }}
  dependsOn:
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}
{{- if .Values.istiooperator.values.revision }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator-{{ .Values.istiooperator.values.revision }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: istio-operator
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
spec:
  targetNamespace: istio-operator
  chart:
    spec:
      chart: {{ .Values.istiooperator.git.path }}
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: istio-operator{{- if .Values.istiooperator.gitupgrade }}-upgrade{{- end }}
        namespace: {{ .Release.Namespace }}

  {{- toYaml $fluxSettingsIstioOperator | nindent 2 }}

  {{- if .Values.istiooperator.postRenderers }}
  postRenderers:
  {{ toYaml .Values.istiooperator.postRenderers | nindent 4 }}
  {{- end }}
  values:
    tag: {{- .Values.istiooperator.values.upgrade }}
  valuesFrom:
    - name: {{ .Release.Name }}-istio-operator-values
      kind: Secret
      valuesKey: "common"
    - name: {{ .Release.Name }}-istio-operator-values
      kind: Secret
      valuesKey: "defaults"
    - name: {{ .Release.Name }}-istio-operator-values
      kind: Secret
      valuesKey: "overlays"

  {{- if .Values.gatekeeper.enabled }}
  dependsOn:
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
  {{- end }}
{{- end }}
